--------------------------------------------------------
--  File created - Sunday-September-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CURRENCYFAIR
--------------------------------------------------------

  CREATE TABLE "KUSHAL"."CURRENCYFAIR" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"CURRENCYFROM" VARCHAR2(20 BYTE), 
	"CURRENCYTO" VARCHAR2(20 BYTE), 
	"AMOUNTSELL" VARCHAR2(20 BYTE), 
	"AMOUNTBUY" VARCHAR2(20 BYTE), 
	"RATE" VARCHAR2(20 BYTE), 
	"TIMEPLACED" TIMESTAMP (6), 
	"ORIGINATINGCOUNTRY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KUSHAL.CURRENCYFAIR
SET DEFINE OFF;
Insert into KUSHAL.CURRENCYFAIR (USERID,CURRENCYFROM,CURRENCYTO,AMOUNTSELL,AMOUNTBUY,RATE,TIMEPLACED,ORIGINATINGCOUNTRY) values ('76420','INR','EUR','9486','364.1','.3548',to_timestamp('26-NOV-11 10.27.44.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'IN');
Insert into KUSHAL.CURRENCYFAIR (USERID,CURRENCYFROM,CURRENCYTO,AMOUNTSELL,AMOUNTBUY,RATE,TIMEPLACED,ORIGINATINGCOUNTRY) values ('134256','EUR','GBP','1000','747.1','.7471',to_timestamp('24-JAN-15 10.27.44.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'FR');
Insert into KUSHAL.CURRENCYFAIR (USERID,CURRENCYFROM,CURRENCYTO,AMOUNTSELL,AMOUNTBUY,RATE,TIMEPLACED,ORIGINATINGCOUNTRY) values ('89461','GBP','INR','3154','248.1','.5486',to_timestamp('17-MAY-16 10.27.44.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'US');
--------------------------------------------------------
--  Constraints for Table CURRENCYFAIR
--------------------------------------------------------

  ALTER TABLE "KUSHAL"."CURRENCYFAIR" MODIFY ("USERID" NOT NULL ENABLE);
